# Functional biodiversity shifts within and across benthic habitats under ocean acidification ----------------------
## Núria Teixidó*, Enric Ballesteros, Samir Alliouane, Maria Cristina Gambi, Jean-Pierre Gattuso, Kristy 
## Kroeker, Fiorenza Micheli, Alice Mirasole, Sebastien Villéger, Cinzia De Vittor, Valeriano Parravacini 
## *corresponding author. Email: nuria.teixido@imev-mer.fr; nuria.teixido@szn.it 

## Loading empty lists and empty vectors ---------------------------------------------------------------------------

# Empty lists
Sample_low_cave         <- vector("list", length = n) 
Sample_amb_cave         <- vector("list", length = n) 
Sample_low_deep         <- vector("list", length = n) 
Sample_amb_deep         <- vector("list", length = n) 
Sample_low_reef         <- vector("list", length = n) 
Sample_amb_reef         <- vector("list", length = n) 
Sample_low_shallow      <- vector("list", length = n) 
Sample_amb_shallow      <- vector("list", length = n) 
cave_FEs_low            <- vector("list", length = n) 
cave_FEs_amb            <- vector("list", length = n)
deep_reef_FEs_low       <- vector("list", length = n) 
deep_reef_FEs_amb       <- vector("list", length = n)
reef_FEs_low            <- vector("list", length = n) 
reef_FEs_amb            <- vector("list", length = n)
shallow_reef_FEs_low    <- vector("list", length = n) 
shallow_reef_FEs_amb    <- vector("list", length = n)
data_random             <- vector("list", length = n)
quadrats_species_cover0 <- vector("list", length = n) 
quadrats_species_cover  <- vector("list", length = n)
species_sumcover        <- vector("list", length = n) 
species_notraits        <- vector("list", length = n) 
sp_nm                   <- vector("list", length = n) 
sp_tr_2                 <- vector("list", length = n) 
sp_to_fe                <- vector("list", length = n) 
fe_nm                   <- vector("list", length = n)
fe_sp                   <- vector("list", length = n) 
fe_tr                   <- vector("list", length = n)
quadrats_fe_cover       <- vector("list", length = n) 
sp_k                    <- vector("list", length = n)
habph_species_cover     <- vector("list", length = n) 
habph_fe_cover          <- vector("list", length = n)
quadrat_covertot        <- vector("list", length = n) 
quadrat_nbsp            <- vector("list", length = n)
quadrat_nbFE            <- vector("list", length = n) 
quadrat_sup4FE          <- vector("list", length = n)
fe_fe_dist              <- vector("list", length = n) 
fe_fspaces              <- vector("list", length = n)
fe_4D_coord             <- vector("list", length = n) 
quadrats_multidimFD     <- vector("list", length = n)
habph_multidimFD        <- vector("list", length = n) 
quadrats_taxo_hill      <- vector("list", length = n)
quadrats_funct_hill     <- vector("list", length = n) 
quadrats_biodiv         <- vector("list", length = n)
quadrats_betax_hill     <- vector("list", length = n) 
quadrats_befun_hill     <- vector("list", length = n)
quadrats_beta_hill      <- vector("list", length = n)
beta_df                 <- vector("list", length = n) 
beta_df.fun             <- vector("list", length = n)
divf                    <- vector("list", length = n) 
beta_long_fun           <- vector("list", length = n)
groupf                  <- vector("list", length = n) 
modf                    <- vector("list", length = n)
beta_df.taxo            <- vector("list", length = n) 
divtaxo                 <- vector("list", length = n)
beta_long_taxo          <- vector("list", length = n) 
groupt                  <- vector("list", length = n) 
modtaxo                 <- vector("list", length = n)
tab                     <- vector("list", length = n)       
pH_hab_mean             <- vector("list", length = n) 
pH_hab_se               <- vector("list", length = n)
cave_sp_FEs_Low         <- vector("list", length = n)  
cave_sp_FEs_Amb         <- vector("list", length = n)
sp_tr_FEs_Low           <- vector("list", length = n)  
sp_tr_FEs_Amb           <- vector("list", length = n)
sp_tr_FEs               <- vector("list", length = n)
deep_reef_sp_FEs_Low    <- vector("list", length = n) 
deep_reef_sp_FEs_Amb    <- vector("list", length = n)
sp_tr_FEs_Low           <- vector("list", length = n) 
sp_tr_FEs_Amb           <- vector("list", length = n)
reef_sp_FEs_Low         <- vector("list", length = n)  
reef_sp_FEs_Amb         <- vector("list", length = n)
sp_tr_FEs_Low           <- vector("list", length = n)  
sp_tr_FEs_Amb           <- vector("list", length = n)
shallow_reef_sp_FEs_Low <- vector("list", length = n) 
shallow_reef_sp_FEs_Amb <- vector("list", length = n)
sp_tr_FEs_Low           <- vector("list", length = n) 
sp_tr_FEs_Amb           <- vector("list", length = n)
habph2_fe_cover         <- vector("list", length = n) 
habph2_multidimFD       <- vector("list", length = n)
data_stat_FEs           <- vector("list", length = n)
RS                      <- vector("list", length = n)
pool_coord              <- vector("list", length = n)
species_avg_pst         <- vector("list", length = n)
asb_sp_relatw           <- vector("list", length = n)
pcoa_fun                <- vector("list", length = n) 
pcoa_taxo               <- vector("list", length = n) 
x.fun                   <- vector("list", length = n) 
x.tax                   <- vector("list", length = n)
data_trait_occupancy    <- vector("list", length = n)
FE_tr_infos             <- vector("list", length = n)

# Empty vectors
FE_C_low   <- rep(NA, n)
FE_C_amb   <- rep(NA, n) 
FE_DR_low  <- rep(NA, n) 
FE_DR_amb  <- rep(NA, n)
FE_R_low   <- rep(NA, n) 
FE_R_amb   <- rep(NA, n)
FE_SR_low  <- rep(NA, n) 
FE_SR_amb  <- rep(NA, n)